name: Build

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - README.md
      - LICENSE
      - .github/*
      - .gitattributes
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - README.md
      - LICENSE
      - .github/*
      - .gitattributes
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Build
      run: ./gradlew build --stacktrace --warning-mode=fail
    - name: Upload build results
      uses: actions/upload-artifact@v3
      with:
        path: build/libs/*.jar
